name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: تكوين إعدادات RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name "fAllowUnsolicited" -Value 1 -ErrorAction SilentlyContinue
          Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name "fAllowUnsolicitedFull" -Value 1 -ErrorAction SilentlyContinue
          netsh advfirewall firewall delete rule name="RDP-Tailscale"
          netsh advfirewall firewall add rule name="RDP-Tailscale" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      - name: إنشاء مستخدم RDP
        run: |
          $password = "MONAFali12"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force

          if (-not (Get-LocalUser -Name "MONAF" -ErrorAction SilentlyContinue)) {
              New-LocalUser -Name "MONAF" -Password $securePass -AccountNeverExpires
          }

          Add-LocalGroupMember -Group "Administrators" -Member "MONAF"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "MONAF"

          echo "RDP_CREDS=User: MONAF | Password: $password" >> $env:GITHUB_ENV

          if (-not (Get-LocalUser -Name "MONAF")) {
              Write-Error "فشل إنشاء المستخدم"
              exit 1
          }

      - name: تثبيت Tailscale
        shell: pwsh
        run: |
          $latestVersion = (Invoke-RestMethod -Uri "https://pkgs.tailscale.com/stable/?mode=json" | Select-Object -First 1).version
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-$latestVersion-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"

          Write-Host "جاري تحميل Tailscale الإصدار: $latestVersion"
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          
          $arguments = "/i `"$installerPath`" /quiet /norestart"
          Start-Process "msiexec.exe" -ArgumentList $arguments -Wait -NoNewWindow
          
          if (Test-Path "$env:ProgramFiles\Tailscale\tailscale.exe") {
              Write-Host "تم تثبيت Tailscale بنجاح"
          } else {
              Write-Error "فشل تثبيت Tailscale"
              exit 1
          }
          
          Remove-Item $installerPath -Force -ErrorAction SilentlyContinue

      - name: تشغيل Tailscale
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$env:GITHUB_RUN_ID
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          if (-not $tsIP) {
              Write-Error "فشل الحصول على عنوان IP من Tailscale"
              exit 1
          }
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV

      - name: فحص اتصال RDP
        run: |
          Write-Host "=== فحص الاتصال ==="
          Write-Host "عنوان IP: $env:TAILSCALE_IP"
          
          Write-Host "`nجاري فحص اتصال Ping..."
          ping -n 3 $env:TAILSCALE_IP
          
          Write-Host "`nجاري فحص منفذ RDP (3389)..."
          Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port 3389 -InformationLevel Detailed
          
          Write-Host "`nالاتصالات النشطة على منفذ 3389:"
          netstat -ano | findstr 3389
          
          Write-Host "`nحالة RDP:"
          qwinsta
          
          Write-Host "`nانتهى الفحص. إذا لم تنجح العملية، يرجى مراجعة السجلات أعلاه."

      - name: الحفاظ على الاتصال
        run: |
          Write-Host "`n=== معلومات اتصال RDP ==="
          Write-Host "العنوان: $env:TAILSCALE_IP"
          Write-Host "اسم المستخدم: MONAF"
          Write-Host "كلمة المرور: MONAFali12"
          Write-Host "=========================`n"
          while ($true) {
              Write-Host "[$(Get-Date)] الاتصال نشط - استخدم Ctrl+C في سير العمل لإنهاء الجلسة"
              Start-Sleep -Seconds 300
          }
