name: RDP Setup

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'Duration in minutes (max 360)'
        required: true
        default: '60'
      password:
        description: 'RDP password'
        required: true
        default: 'Admin@12345'

jobs:
  setup-rdp:
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
    - name: Configure RDP
      shell: powershell
      run: |
        # Enable RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
        
        # Configure firewall
        netsh advfirewall firewall delete rule name="RDP" | Out-Null
        netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389 | Out-Null
        Set-NetFirewallRule -DisplayGroup "Remote Desktop" -Enabled True -Profile Any
        Restart-Service TermService -Force

    - name: Create RDP User
      shell: powershell
      run: |
        $password = "${{ github.event.inputs.password }}"
        $securePass = ConvertTo-SecureString $password -AsPlainText -Force

        # Create or update user
        if (Get-LocalUser -Name "RDPUser" -ErrorAction SilentlyContinue) {
            Remove-LocalUser -Name "RDPUser" -Confirm:$false
        }

        New-LocalUser -Name "RDPUser" -Password $securePass -AccountNeverExpires
        Add-LocalGroupMember -Group "Administrators" -Member "RDPUser"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDPUser"
        Enable-LocalUser -Name "RDPUser"

    - name: Get Public IP
      id: get-ip
      shell: powershell
      run: |
        $ip = (Invoke-RestMethod -Uri "https://api.ipify.org?format=json").ip
        echo "ip=$ip" >> $env:GITHUB_OUTPUT

    - name: Show Connection Info
      shell: powershell
      run: |
        $ip = "${{ steps.get-ip.outputs.ip }}"
        $password = "${{ github.event.inputs.password }}"
        $duration = "${{ github.event.inputs.duration }}"
        
        Write-Host "=============================================="
        Write-Host "RDP Connection Information:"
        Write-Host "IP: $ip"
        Write-Host "Username: RDPUser"
        Write-Host "Password: $password"
        Write-Host "Port: 3389"
        Write-Host "Session will be active for $duration minutes"
        Write-Host "=============================================="

    - name: Keep Alive
      shell: powershell
      run: |
        $minutes = [int]"${{ github.event.inputs.duration }}"
        Write-Host "RDP session will be active for $minutes minutes"
        Start-Sleep -Seconds ($minutes * 60)
        Write-Host "RDP session has ended"
